version: '2'
services:
  lapis:
    build:
      context: .
      dockerfile: Dockerfile
    image: ccserver/lapis
    container_name: lapis
    networks:
      - secure_bridge
      - db
    volumes:
      - "./:/var/www/ccserver.info/"
    ports:
      - "127.0.0.1:$PORT:8000"
    expose:
      - "8000"
    user: $RUN_USER
    command: ["lapis", "server"]

  redis:
    image: "redis:latest"
    networks:
      - db
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    user: $RUN_USER

networks:
  secure_bridge:
    external: true
  db:
