@startuml
title ModからDBに直接書き込むパターン

actor User as "鯖民"
User -> Minecraft: ログイン
database DB
activate Minecraft

alt ゲーム内操作
    User -> Minecraft: トークン要求
    Minecraft -> DB: トークン保存
    note left: トークン生成
    activate DB
    deactivate DB
    User <-- Minecraft: プライベートチャット経由でトークン返却
end

User -> Minecraft: ログアウト
deactivate Minecraft
note right: この時点でユーザはゲームをログアウトしてもよい

User -> WebApp: ログイン試行
activate WebApp
WebApp -> DB: トークン検索
activate DB
return
deactivate DB
User <-- WebApp

User <-> WebApp: 諸々
@enduml